language: java

jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk6

env:
  - TERM=dumb

before_install:
 - chmod +x gradlew
 
before_script:
 - chmod +x gradlew

script:
  - ./gradlew assemble -x test

branches:
 only:
 - master


